CREATE OR REPLACE procedure DELL_OPTI.bad_metrics
is
  x int := 1;
begin
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 2) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
  end loop;
  for a in 1 .. 100 loop
    for b in 1 .. 100 loop
      if    (x = -1) then
        x := x + 1;
      elsif (x = 0) then
        x := x + 2;
      elsif (x = 1) then
        x := x + 3;
      else
        x := x + 4;
      end if;
    end loop;
 end loop;
end;
/
